server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/davis
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.common.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update